[ADD] DEVELOPをマージ

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -42,9 +42,13 @@ jobs:
 
       - run: yarn install
 
+      - run:
+         name: 'wait for db'
+         command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
+
       # データベースのセットアップ
       - run: mv config/database.ci.yml config/database.yml
-      - run: RAILS_ENV=test bundle exec rake db:create db:migrate db:schema:load
+      - run: RAILS_ENV=test bundle exec rake db:create db:schema:load
 
       # テストを実行
       - run:
@@ -58,6 +62,25 @@ jobs:
                             --out /tmp/test-results/rspec.xml \
                             --format progress \
                             $TEST_FILES
+
+      - run: sudo apt-get install bc
+      - run:
+          name: Check spec diff
+          command: |
+            COVERAGE=`cat coverage/.last_run.json | jq '.result.covered_percent'`
+            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
+              url="$(echo "$CIRCLE_PULL_REQUEST" | sed 's/https:\/\/github.com\//https:\/\/api.github.com\/repos\//' | sed 's/\/pull\//\/pulls\//')?access_token=$GITHUB_TOKEN"
+              HEAD_BRANCH=$(curl "$url" | jq -r '.base.ref')
+            fi
+            echo COVERAGE: $COVERAGE
+            echo 'HEAD_BRANCH: ' ${HEAD_BRANCH}
+            BASE_BRANCH=${CIRCLE_BRANCH}
+            echo 'BASE_BRANCH: ' ${BASE_BRANCH}
+            diff=$(git diff --name-only origin/$HEAD_BRANCH origin/$BASE_BRANCH | grep -E 'spec/')
+            error=false
+            if test -n "$diff" -a `echo "50.0 > $COVERAGE" | bc` -eq 1 ; then error=false; else error=true; fi
+            if $error; then exit 1; fi
+            exit 0
 
       # テスト結果を保存
       - store_test_results:
